
server:
  port: 8081

ecos:
  webapp:
    dataSources:
      main:
        url: jdbc:postgresql://localhost:5431/uiserv
        username: uiserv
        password:

application:
  default-theme-id: citeckTheme
  #Раньше располагался в конфиге ecos под тем же названием
  menu-config-authority-order:

uiserv:
  alfresco-service-url: 'http://alfresco/alfresco/s/'
  config:
    tabs-enabled:
      value: true
    language-switcher-enabled:
      value: true
    custom-create-buttons:
      value: '[]'
    restrict-access-to-edit-dashboard:
      value: false
    active-theme:
      value: ecos

  ecos-types-sync.active: true

ecos-app:
  id: ecos-uiserv
  version: 1.4.0
  name: UI Server

# Persisted user configurations limit. If exceeded, the latest configuration is deleted
max-user-configurations-persisted: 1000
