
# fix for windows and macos to allow microservices in docker send requests to this app

eureka:
  instance:
    hostname: host.docker.internal
    ip-address: host.docker.internal

# force setup host and port of microservices to fix requests sending from this app

alfresco:
  ribbon:
    listOfServers: localhost:8080
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

eapps:
  ribbon:
    listOfServers: localhost:8089
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

emodel:
  ribbon:
    listOfServers: localhost:8094
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

