# force setup host and port of microservices to fix requests sending from this app

alfresco:
  ribbon:
    listOfServers: localhost:8080
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

eapps:
  ribbon:
    listOfServers: localhost:8089
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
  watcher:
    artifacts:
      enabled: true
      locations: './src/main/resources/eapps/artifacts'

emodel:
  ribbon:
    listOfServers: localhost:8094
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

