
alfresco:
    ribbon:
        listOfServers: localhost:8080
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

eapps:
    ribbon:
        listOfServers: localhost:8089
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

emodel:
    ribbon:
        listOfServers: localhost:8094
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

