---
id: custom-report-issue-url
name:
  ru: URL для отчета о проблеме
  en: URL for issue report
value: >
  mailto:support@citeck.ru?subject=Ошибка в работе Citeck ECOS:
  краткое описание&body=Summary: Короткое описание проблемы (продублировать в теме письма)
  %0A%0ADescription:%0AПожалуйста, детально опишите возникшую проблему, последовательность
  действий, которая привела к ней. При необходимости приложите скриншоты.

valueDef:
  formRef: uiserv/form@config-textarea
