version: '3'
services:
    ui:
        container_name: ecos-ui-develop
        ports:
            - 80:80/tcp
        image: nexus.citeck.ru/ecos-ui:1.6.0-snapshot
        environment:
            - PROXY_TARGET=host.docker.internal:8080
            - GATEWAY_TARGET=host.docker.internal:8085
            - CADVISOR_TARGET=<CADVISOR_TARGET
            - API_AUTH_TARGET=<API_AUTH_TARGET
        depends_on:
            - gateway-app
    gateway-app:
        image: ecos-gateway:draft
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-psql:5432/gateway
            - JHIPSTER_SLEEP=30
        ports:
            - 8085:8085
        links:
            - jhipster-registry
            - gateway-psql
        depends_on:
            - gateway-psql
            - jhipster-registry
    jhipster-registry:
        image: jhipster/jhipster-registry:v4.1.1
        volumes:
            - ./central-server-config/:/central-config
            # When run with the "dev" Spring profile, the JHipster Registry will
            # read the config from the local filesystem (central-server-config directory)
            # When run with the "prod" Spring profile, it will read the configuration from a Git repository
            # See https://www.jhipster.tech/microservices-architecture/#registry_app_configuration
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_SECURITY_USER_PASSWORD=admin
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:/central-config/docker-config/
        ports:
            - 8761:8761
    rabbitmq:
        image: "rabbitmq:3-management"
        restart: on-failure:5
        container_name: rabbitmq
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
            - RABBITMQ_DEFAULT_VHOST=/
        ports:
            - 15672:15672/tcp
            - 5672:5672/tcp
        volumes:
            - /opt/rabbitmqdata:/var/lib/rabbitmq
    gateway-psql:
        image: postgres:10.4
        ports:
            - 5430:5432
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
        volumes:
            - psql_gateway:/var/lib/postgresql/data
    uiserv-psql:
        image: postgres:10.4
        ports:
            - 5431:5432
        environment:
            - POSTGRES_USER=uiserv
            - POSTGRES_PASSWORD=
        volumes:
            - psql_uiserv:/var/lib/postgresql/data
    eapps-psql:
        image: postgres:10.4
        ports:
            - 5437:5432
        environment:
            - POSTGRES_USER=eapps
            - POSTGRES_PASSWORD=
        volumes:
            - psql_eapps:/var/lib/postgresql/data
volumes:
    psql_eapps:
        external: true
    psql_gateway:
        external: true
    psql_uiserv:
        external: true
    rabbitmq_data:
        external: true

# Create volumes for DB:
#
# docker volume create --name=rabbitmq_data
# docker volume create --name=psql_eapps
# docker volume create --name=psql_gateway
# docker volume create --name=psql_uiserv
